= 바이너리 빌드
:navtitle: 바이너리 빌드

include::vars.adoc[]

[#moving_on_from_s2i]
== S2I를 넘어서
앞서 확인했듯이 S2I는 소스 코드에서 컨테이너로 가는 훌륭한 방법이지만, 매일 빠르게 반복하는
개발 작업을 하기에는 이 과정이 다소 느립니다. 예를 들어 CSS를 조금 바꾸거나 클래스의 메서드 하나를
변경하고 싶을 때, 전체 git commit과 빌드 사이클을 거치고 싶지는 않을 것입니다. 이 실습에서는
빠르게 반복 작업을 하는 더 효율적인 방법을 보여드립니다. 그 과정에서 코드를 디버깅하는 방법도
함께 살펴보겠습니다.

이제 MLB parks service를 빌드했으니, 빠른 변경 작업을 몇 가지 해보겠습니다.

[#fast_iterative_code_change_using_binary_deploy]
== 바이너리 배포를 사용한 빠른 반복 코드 변경

OpenShift 명령줄은 로컬 머신에서 배포를 수행하는 기능을 제공합니다. 이 경우 S2I를 사용하되,
로컬 머신에 있는 war 파일을 그대로 가져와 이미지에 담도록 OpenShift에 지시합니다.

이런 개발 패턴을 사용하면 로컬 머신에서 빠르게 빌드하고(로컬 캐시와 머신의 모든 성능을
활용하여) war 파일만 빠르게 업로드할 수 있습니다.

NOTE: 실제로 작업 디렉터리 전체를 S2I 빌더에 전송하여 OpenShift에서 Maven 빌드를 수행하도록 하는 방식으로도 이 패턴을 사용할 수 있습니다. 로컬 디렉터리를 사용하면 로컬 머신에 Maven이나 다른 Java 툴체인을 설치할 필요가 없어지고
// 또한 git commit과 push도 필요하지 않게 됩니다. 자세한 내용은
// {openshift-docs-url}/builds/basic-build-operations.html#builds-basic-start-source_basic-build-operations[공식 문서]에서 확인하세요.


[#using_binary_deployment]
== 실습: 바이너리 배포 사용하기

[#clone_source]
=== 소스 클론하기
첫 번째 단계는 GitHub에서 MLB 소스 코드를 워크샵 환경으로 클론하는 것입니다:

[.console-input]
[source,bash]
----
git clone https://github.com/openshift-roadshow/mlbparks.git
----

NOTE: 이 가이드의 스크린샷에서는 IntelliJ를 사용하고 있지만 어떤 툴체인을 사용하든 상관없이 동작해야 합니다. JBoss
Developer Studio와 JBoss Developer Tools는 IDE 안에서 거의 매끄럽게 이 작업을 수행할 수 있는 내장 기능을 제공합니다.

[#setup_the_build_of_the_war_file]
=== WAR 파일 빌드 설정하기
로컬 머신에 Maven이 모두 설정되어 있다면 ``mlbparks`` 디렉터리로 ``cd``한 후 ``mvn package``를 실행하면 됩니다.

[#docker_for_maven]
[TIP]
====
로컬 머신에 Maven이 없지만 docker를 실행할 수 있다면, 대신 저장소 디렉터리를 마운트하여 컨테이너 안에서 빌드 명령을 실행할 수 있습니다.

. 위에서 ``git clone``을 실행한 디렉터리 안에서 다음 명령을 실행합니다:
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
docker run -it --rm --user 0 --name maven_builder -v ~/.kube:/home/jboss/.kube -v $(pwd):/workspaces -w /workspaces registry.access.redhat.com/ubi8/openjdk-11 /bin/bash
----
+
. 다음으로, (컨테이너 안에서) 다음 명령을 실행하여 컨테이너에 최신 버전의 ``oc``를 로컬로 설치합니다
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
mkdir -p $HOME/bin && curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | \
    tar -xvzf - -C $HOME/bin/ oc && chmod 755 $HOME/bin/oc && ln -s $HOME/bin/oc $HOME/bin/kubectl
----
+
. 마지막으로, 다음을 실행하고 출력을 비교하여 빌더 컨테이너 안에서도 여전히 OpenShift 클러스터에 연결되어 있는지 확인합니다:
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc whoami --show-server
----
+
[.console-output]
[source,bash,subs="+macros,+attributes"]
----
https://{ocp4_starter_apps_domain}:30713
----

완료되면 아래 안내된 명령들을 그대로 따라 할 수 있습니다.
====

[.console-input]
[source,bash,subs="+attributes,macros+"]
----
cd mlbparks
mvn package
----

ROOT.war의 출력 위치를 잘 기억해 두세요. 나중에 해당 디렉터리가 필요합니다.

[#code_change]
=== 코드 변경

이제 소스 코드를 변경할 시간입니다!

다음 경로에서 ``BackendController`` Java 클래스를 편집합니다:

[.console-output]
[source,bash]
----
src/main/java/com/openshift/evg/roadshow/rest/BackendController.java
----

이는 서비스에 대한 기본 정보를 제공하는 REST 엔드포인트이며 다음 위치에서 확인할 수 있습니다:

[source,bash,role="copypaste",subs="+attributes"]
----
http://mlbparks-{ocp4_starter_project}.{ocp4_starter_apps_domain}/ws/info/
----

23번째 줄을 변경하여 "MLB Parks" 앞에 _AMAZING_을 추가해서 다음과 같이 만드세요:

[source,java]
----
return new Backend("mlbparks", "AMAZING MLB Parks", new Coordinates("39.82", "-98.57"), 5);
----

파일을 저장하는 것을 잊지 말고, 소스 폴더의 루트에서 ``mvn package``를 다시 실행하세요:

[.console-input]
[source,bash,subs="+attributes,macros+"]
----
mvn package
----

[#doing_the_binary_build]
=== 바이너리 빌드 수행하기

자, war 파일 빌드가 끝났으니 이를 사용해서 빌드를 시작해 보겠습니다.

Maven으로 war를 빌드했다면:

[.console-input]
[source,bash,subs="+attributes,macros+"]
----
oc start-build bc/mlbparks --from-file=target/ROOT.war --follow
----

NOTE: 터미널에서 빌드 출력을 따라가고 싶다면 --follow는 선택 사항입니다.

레이블과 recreate 배포 전략을 사용하면, 새 배포가 끝나는 즉시 지도 이름이 업데이트됩니다. recreate 배포 전략에서는 새 배포를 수행하기 전에 먼저 pod를 내립니다.
pod가 내려가면 parksmap service는 레이어에서 MLBParks 지도를 제거합니다. pod가 다시 올라오면 레이어가
새 제목과 함께 자동으로 다시 추가됩니다. 이는 rolling 배포에서는 일어나지 않는 현상인데, rolling 배포는
기존 버전의 pod를 내리기 전에 새 버전의 pod를 먼저 띄우기 때문입니다. rolling 전략은 무중단 배포를 가능하게 합니다.

Topology 화면에서 진행 중인 배포를 확인할 수 있으며, 완료되면 다음 위치에서 새로운 콘텐츠를 확인할 수 있습니다:

[source,bash,role="copypaste",subs="+attributes"]
----
http://mlbparks-{ocp4_starter_project}.{ocp4_starter_apps_domain}/ws/info/
----

이렇게 빌드와 배포 프로세스를 어떻게 빠르게 할 수 있는지 살펴보았습니다.
